### ISSUE TITLE
(ESRGAN) Cannot initialize CUDA without ATen_cuda library.

### ISSUE THREAD

**Issue by Clanf** [natethegreate/hentAI#13]
mosaic (DCP) work fine with cuda GPU, but trying to use mosaic (ESRGAN) gives this -

`Starting ESRGAN detection and decensor
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Clanf\AppData\Local\Programs\Python\Python36\lib\tkinter\__i
nit__.py", line 1705, in __call__
    return self.func(*args)
  File "main.py", line 311, in <lambda>
    go_button = Button(mos_win, text="Go!", command = lambda: hentAI_TGAN(in_pat
h=o_entry.get(), is_video=False))
  File "main.py", line 184, in hentAI_TGAN
    detect_instance.run_ESRGAN(in_path = in_path, is_video = is_video, force_jpg
 = force_jpg)
  File "D:\hent-AI\detector.py", line 377, in run_ESRGAN
    self.esrgan_instance = ColabESRGAN.test.esrgan(model_path=self.esr_model_pat
h, hw=self.hardware)
  File "D:\hent-AI\ColabESRGAN\test.py", line 24, in __init__
    self.model = self.model.to(self.device)
  File "C:\Users\Clanf\AppData\Local\Programs\Python\Python36\lib\site-packag
es\torch\nn\modules\module.py", line 379, in to
    return self._apply(convert)
  File "C:\Users\Clanf\AppData\Local\Programs\Python\Python36\lib\site-packag
es\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "C:\Users\Clanf\AppData\Local\Programs\Python\Python36\lib\site-packag
es\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "C:\Users\Clanf\AppData\Local\Programs\Python\Python36\lib\site-packag
es\torch\nn\modules\module.py", line 191, in _apply
    param.data = fn(param.data)
  File "C:\Users\Clanf\AppData\Local\Programs\Python\Python36\lib\site-packag
es\torch\nn\modules\module.py", line 377, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits i
ts backend into two shared libraries: a CPU library and a CUDA library; this err
or has occurred because you are trying to use some CUDA functionality, but the C
UDA library has not been loaded by the dynamic linker for some reason.  The CUDA
 library MUST be loaded, EVEN IF you don't directly use any symbols from the CUD
A library! One common culprit is a lack of -Wl,--no-as-needed in your link argum
ents; many dynamic linkers will delete dynamic library dependencies if you don't
 depend on any of their symbols.  You can check if this has occurred by using ld
d on your binary to see if there is a dependency on *_cuda.so library.`

**Comment by Clanf** [comment]
sorry for messy log, github doesn't work properly on my browser, can't preview post, can't edit, and apparently can't properly post
